image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mongod --dbpath data   
    # command: mkdir -p data && mongod --dbpath data
  - name: install npm modules and start server  
    command: npm i --save nodemon axios morgan cors express body-parser mongoose multer fs path del dotenv handlebars && npm start